### ISSUE TITLE
Vehicle Servicepoint

### ISSUE THREAD

**Issue by fingerratte** [Huber-Sepp/Liberation-RX-MilSim-United#48]

**Comment by fingerratte** [comment]
Land Vehicle Service Point that allows different ammunition for Vehicle Turrets.

**Comment by Sonic47** [comment]
Service ist nicht public kann aber mal nach fragen. Wenn interesse

**Comment by Sonic47** [comment]
Wir dürfen nicht.

**Comment by fingerratte** [comment]
Von wem ist der denn der richtige?
